model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQLucidrainsModel
  params:
    monitor: val/rec_loss_epoch
    embed_dim: 256
    dim: 256
    codebook_dim: 256
    n_embed: 1024
    codebook_size: 1024
    use_cosine_sim: True
    kmeans_init: True
    kmeans_iters: 10
    threshold_ema_dead_code: 2
    accept_image_fmap: True
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 0.8
        codebook_weight: 1.0


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 10
    train:
      target: taming.data.faceshq.FFHQTrain
      params:
        size: 256
    validation:
      target: taming.data.faceshq.FFHQValidation
      params:
        size: 256
